#! /bin/sh

sxhkd &

bspc monitor HDMI-0 -d I II III
bspc monitor DVI-D-0 -d IV V VI VII

sh ~/.config/polybar/launch.sh

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom --experimental-backends

feh --no-fehbg --bg-fill $HOME/Pictures/Wallpapers/horizon-theme/horizon.png

killall -9 sxhkd dunst 

sxhkd &
lxpolkit &
xsetroot -cursor_name left_ptr &
dunst &
discord &
slack &
flameshot &

notify-send "Bem vindo Jonas"






